name: Pipe CI Java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  schedule:
    - cron: '0 12 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: '15'
        distribution: 'adopt'
        cache: maven
        
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
              
    - name: Build Project
      run: mvn install -Dmaven.test.skip=true

    - name: Running the tests
      run: mvn test -Dcucumber.options="--tags @test"

    - name: Deploying report in gh-pages
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./output
